### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by wlhm1984** [hdijkema/QRibbon#2]
您好，我检出您的项目，编译报错，能否给予指导，非常感谢！
错误信息如下，是qt版本不对吗？我用的qt5.5.1最新的。
1>------ Rebuild All started: Project: QRibbon, Configuration: Release x64 ------
1>  Moc'ing qribbon.h...
1>  Moc'ing qribbonsection.h...
1>  Rcc'ing qribbon.qrc...
1>  qribbon.cpp
1>  qribbonbutton.cpp
1>  qribbonsection.cpp
1>  Generating Code...
1>     Creating library release\QRibbon.lib and object release\QRibbon.exp
1>qribbon.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const \* __cdecl QRibbon::metaObject(void)const " (?metaObject@QRibbon@@UEBAPEBUQMetaObject@@XZ)
1>qribbon.obj : error LNK2001: unresolved external symbol "public: virtual void \* __cdecl QRibbon::qt_metacast(char const *)" (?qt_metacast@QRibbon@@UEAAPEAXPEBD@Z)
1>qribbon.obj : error LNK2001: unresolved external symbol "public: virtual int __cdecl QRibbon::qt_metacall(enum QMetaObject::Call,int,void \* *)" (?qt_metacall@QRibbon@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)
1>qribbon.obj : error LNK2019: unresolved external symbol "public: void __cdecl QRibbon::ribbonVisibilityChanged(bool)" (?ribbonVisibilityChanged@QRibbon@@QEAAX_N@Z) referenced in function "protected: void __cdecl QRibbon::hideShow(void)" (?hideShow@QRibbon@@IEAAXXZ)
1>qribbon.obj : error LNK2019: unresolved external symbol "public: void __cdecl QRibbon::currentIndexChanged(int)" (?currentIndexChanged@QRibbon@@QEAAXH@Z) referenced in function "public: void __cdecl QRibbon::setCurrentIndex(int)" (?setCurrentIndex@QRibbon@@QEAAXH@Z)
1>qribbon.obj : error LNK2019: unresolved external symbol "public: void __cdecl QRibbon::tabTextChanged(int,class QString const &)" (?tabTextChanged@QRibbon@@QEAAXHAEBVQString@@@Z) referenced in function "public: void __cdecl QRibbon::setTabText(int,class QString const &)" (?setTabText@QRibbon@@QEAAXHAEBVQString@@@Z)
1>qribbon.obj : error LNK2019: unresolved external symbol "public: static struct QMetaObject const QRibbon::staticMetaObject" (?staticMetaObject@QRibbon@@2UQMetaObject@@B) referenced in function "public: static class QString __cdecl QRibbon::tr(char const *,char const *,int)" (?tr@QRibbon@@SA?AVQString@@PEBD0H@Z)
1>qribbon.obj : error LNK2019: unresolved external symbol "public: static struct QMetaObject const QRibbonSection::staticMetaObject" (?staticMetaObject@QRibbonSection@@2UQMetaObject@@B) referenced in function "public: static class QString __cdecl QRibbonSection::tr(char const *,char const *,int)" (?tr@QRibbonSection@@SA?AVQString@@PEBD0H@Z)
1>qribbonsection.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QRibbonSection::staticMetaObject" (?staticMetaObject@QRibbonSection@@2UQMetaObject@@B)
1>qribbonsection.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const \* __cdecl QRibbonSection::metaObject(void)const " (?metaObject@QRibbonSection@@UEBAPEBUQMetaObject@@XZ)
1>qribbonsection.obj : error LNK2001: unresolved external symbol "public: virtual void \* __cdecl QRibbonSection::qt_metacast(char const *)" (?qt_metacast@QRibbonSection@@UEAAPEAXPEBD@Z)
1>qribbonsection.obj : error LNK2001: unresolved external symbol "public: virtual int __cdecl QRibbonSection::qt_metacall(enum QMetaObject::Call,int,void \* *)" (?qt_metacall@QRibbonSection@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)

**Comment by hdijkema** [comment]
Dit you rerun 'qmake'?

**Comment by wlhm1984** [comment]
no，i open QRibbon.pro with qt then build,my qt version is '5.5.1'.

**Comment by hdijkema** [comment]
Try running qmake first (I'm using QCreator)

Op 25-1-2016 om 10:34 schreef wlhm1984:

> no，i open QRibbon.pro with qt then build,my qt version is '5.5.1'.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/hdijkema/QRibbon/issues/2#issuecomment-174449268.

## 

Hans Dijkema
Weerdslag 64
7206BT Zutphen

tel. 06 4639 0827
email: hans@dykema.nl mailto:hans@dykema.nl

**Comment by wlhm1984** [comment]
thanks for your  reply,i try run qmake first ,build still unsuccess .i have no idea.

**Comment by ghost** [comment]
@wlhm1984 What does your development environment look like?

**Comment by hdijkema** [comment]
Dear wlhm1984,

You need to create a separate compiler configuration: Like this:
This will add the configuration: 'app' to your qmake configuration and 
will compile the QRibbon test application.

![chhibhbi](https://cloud.githubusercontent.com/assets/745693/13103514/3783a96e-d557-11e5-9867-cf4d06777f14.png)

Op 17-2-2016 om 04:59 schreef Dongyang LI:

**Comment by hdijkema** [comment]
I had some open commits on my local machine, which weren't on GitHub. Now they are.
